defaults:
  - logger: wandb
  - callbacks: default

_target_: lightning.Trainer
accelerator: auto
strategy: auto
devices: 1

deterministic: false

fast_dev_run: false

min_epochs: 1
max_epochs: 100

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like checkpoints and metrics
default_root_dir: ${hydra:runtime.output_dir}

detect_anomaly: false

#
gradient_clip_val: 0.5
log_every_n_steps: 10
check_val_every_n_epoch: 1
