debug: False

model:
  schnet_hidden_channels: 512
  schnet_num_filters: 256
  schnet_num_interactions: 5
  schnet_num_gaussians: 50

  vit_embed_dim: 256
  vit_depth: 6
  vit_num_heads: 8
  vit_patch_size: 4
